// FAQPage JSON-LD — gives expandable FAQ rich snippets directly in Google search results
// These appear as dropdown accordions under your listing — takes up much more space = more clicks

export const FAQS = {
  en: [
    { q: "Do you offer international shipping for commercial kitchen machine accessories and spare parts?",
      a: "Yes, HDO Global Trade provides fast and reliable worldwide shipping for all commercial kitchen machine accessories and spare parts. We ensure your orders reach you quickly, regardless of your location. Every shipment includes a full order tracking number from the moment of dispatch until it reaches your commercial kitchen, giving you complete peace of mind." },
    { q: "Are your commercial kitchen machine accessories and spare parts tested for quality before shipping?",
      a: "Absolutely. At HDO Global Trade, quality and reliability are our top priorities. Every commercial kitchen machine accessory and spare part undergoes rigorous quality control checks performed by our certified technical team. Before leaving our warehouse, each item is individually inspected and tested to ensure it meets professional standards, guaranteeing you receive high-quality, functional components ready for installation." },
    { q: "How can I find the exact spare part for my kitchen equipment?",
      a: "Finding the right component is simple with our search tools. You can locate your spare part by searching for: Manufacturer/Brand Name, Part Reference Number (OEM), or Equipment Category (Dishwashers, Planetary Mixers, Juicers, Vegetable Cutters, Commercial Ovens, Hand Mixers, or Kitchen Taps). Still having trouble? Contact us directly via WhatsApp or email with your machine's brand, model, and a photo of the part or data plate." },
    { q: "Do you supply original OEM parts or aftermarket alternatives?",
      a: "At HDO Global Trade, we offer both original OEM spare parts and high-quality compatible aftermarket alternatives. This allows you to make the best choice for your specific machine, technical requirements, and budget. Whether you prefer the exact manufacturer-branded component or a cost-effective, high-performance alternative, our extensive catalog has you covered." },
    { q: "How long does delivery take for commercial kitchen machine accessories and spare parts?",
      a: "At HDO Global Trade, we prioritize fast delivery. Within the EU: Standard delivery typically takes 2–5 business days. International (Outside the EU): Orders typically arrive within 3–7 business days, depending on destination and local customs processing. Express options are available at checkout. All shipments include full tracking so you can monitor your order's progress until it arrives." },
    { q: "Do you supply spare parts for professional and commercial kitchen equipment?",
      a: "Yes, HDO Global Trade is a leading global supplier of high-quality spare parts for commercial kitchen equipment. We support restaurants, hotels, catering companies, and independent repair technicians. Our inventory covers commercial dishwashers, glasswashers, planetary & stand mixers, commercial ovens, vegetable cutters, food processors, commercial juicers, blenders, immersion blenders (hand mixers), and kitchen taps." },
    { q: "Where can I find my commercial kitchen equipment's model number?",
      a: "To ensure you order the correct spare part, you will need your machine's model number and serial number. Check the identification label (data plate) on the back panel, side, or underside of the machine; inside the door frame, behind the filter, or near the control panel; or on the motor housing or base of the unit. Simply snap a photo and send it to our team via WhatsApp (+351935210099). We will cross-reference it with our database and confirm the exact compatible spare parts immediately." },
    { q: "What is your returns policy for spare parts?",
      a: "At HDO Global Trade, we accept returns within 7 days of delivery, provided the parts are unused and in their original packaging and condition. Contact our support team via phone, WhatsApp, or email with your order number and reason for return. After inspection, we will process your refund or exchange promptly. Note: Items must not have been installed or modified." },
    { q: "Do you offer bulk discounts or wholesale pricing for business clients?",
      a: "Yes, HDO Global Trade specializes in B2B partnerships. We offer competitive wholesale pricing and tiered discounts for volume orders for distributors, resellers, commercial kitchen repair workshops, hotel & restaurant chains, and corporate procurement teams. Contact our commercial sales team via phone, WhatsApp, or email for a customized quote tailored to your business needs." },
    { q: "Can I get a VAT-compliant invoice for my business purchase?",
      a: "Yes. We provide VAT-compliant invoices for all purchases, sent to your registered email address. For EU VAT-registered businesses, you may be eligible for an intra-community tax exemption (Reverse Charge mechanism) — enter your valid EU VAT number during checkout and our system will automatically validate and adjust the tax calculation. For non-EU customers, please check your local import tax regulations." },
    { q: "What payment methods do you accept?",
      a: "We accept Credit & Debit Cards (Visa, Mastercard, American Express), Digital Wallets (PayPal), and Direct Bank Transfers (available for wholesale and bulk orders). We support EUR (€), USD ($), and GBP (£). All transactions are processed through Stripe, a globally recognized payment gateway with advanced encryption and fraud protection." },
    { q: "What are your support response times?",
      a: "Urgent WhatsApp Support is available 24/7 for immediate spare part inquiries and technical assistance. Email & Phone Support provides detailed responses and quotes within one business day. Whether you are in the middle of a busy service or planning your maintenance schedule, we ensure fast, professional support exactly when you need it." },
    { q: "Which brands of commercial kitchen equipment do you stock spare parts for?",
      a: "HDO Global Trade stocks spare parts for all major commercial kitchen equipment brands, including Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama, and many more. If you don't see your brand listed, contact us — our sourcing team can locate parts for virtually any commercial kitchen machine manufacturer worldwide." },
    { q: "Do you provide technical support for spare part installation?",
      a: "Yes. Our technical team is available to assist with part identification, compatibility verification, and basic installation guidance. You can reach us via WhatsApp for immediate assistance, or email us with photos of your equipment and the part you need help with. For complex installations, we recommend consulting a certified kitchen equipment technician." },
    { q: "Can I track my order after it has been shipped?",
      a: "Absolutely. Every order shipped from HDO Global Trade includes a full tracking number sent to your registered email address. You can monitor your shipment's progress in real-time from dispatch to delivery. For EU orders, we use premium courier services that provide detailed tracking updates at every stage of the delivery process." },
    { q: "Do you ship to Austria, Germany, and other German-speaking countries?",
      a: "Yes, we ship throughout Europe including Austria (Österreich), Germany (Deutschland), Switzerland, and all EU member states. Deliveries to Austria and Germany typically arrive within 3–5 business days. All orders include full tracking, and EU business customers with a valid VAT number can benefit from the intra-community tax exemption." },
  ],
  pt: [
    { q: "Enviam peças sobresselentes para todo o mundo?",
      a: "Sim, a HDO Trade envia peças testadas para clientes em todo o mundo com entrega rápida e rastreamento completo desde o despacho até à entrega." },
    { q: "Todas as peças são testadas antes do envio?",
      a: "Cada peça vendida sob a marca HDO TRADE é testada individualmente pela nossa equipa técnica certificada e passa por rigoroso controlo de qualidade antes de sair do armazém." },
    { q: "Como posso encontrar a peça certa para a minha máquina?",
      a: "Pesquise por fabricante, categoria ou referência na nossa loja. Pode filtrar por tipo de equipamento — máquina de lavar louça, batedeira, centrifugadora, cortador de legumes ou torneira de cozinha. Se não encontrar, envie-nos mensagem via WhatsApp e localizamos a peça por si." },
    { q: "As vossas peças são originais OEM ou compatíveis?",
      a: "Temos tanto peças originais OEM como alternativas compatíveis de alta qualidade. Cada produto indica claramente se é original ou compatível, para escolher o mais adequado à sua máquina e orçamento." },
    { q: "Quanto tempo demora a entrega?",
      a: "As entregas em Portugal e na UE demoram normalmente 3 a 7 dias úteis. Há opções de envio expresso disponíveis no checkout. Encomendas internacionais fora da UE demoram entre 7 a 14 dias úteis." },
    { q: "Fornecem peças para equipamento de cozinha industrial?",
      a: "Sim, especializamo-nos em peças para equipamento de cozinha profissional e industrial: máquinas de lavar louça comerciais, batedeiras industriais, centrifugadoras, cortadores de legumes e torneiras de cozinha. Servimos restaurantes, hotéis, empresas de catering e técnicos de reparação." },
    { q: "Como encontro o número de modelo da minha máquina?",
      a: "O número de modelo está normalmente numa etiqueta na parte traseira ou inferior da máquina, dentro da porta ou no motor. Partilhe-o connosco via WhatsApp e confirmamos imediatamente as peças compatíveis." },
    { q: "Qual é a política de devoluções?",
      a: "Aceitamos devoluções até 14 dias após a entrega para peças não utilizadas em estado original. Se uma peça chegar danificada ou não corresponder à descrição, substituímos ou reembolsamos na totalidade sem custo para si." },
    { q: "Oferecem preços grossistas para empresas?",
      a: "Sim, oferecemos preços competitivos para restaurantes, oficinas de reparação, cadeias hoteleiras e equipas de compras em volume. Contacte-nos via WhatsApp ou email para um orçamento personalizado." },
    { q: "Posso obter fatura com IVA?",
      a: "Sim. Todas as encomendas geram automaticamente uma fatura com IVA enviada para o seu email. Clientes empresariais da UE com número de IVA válido podem beneficiar de isenção intracomunitária — introduza o NIF/NIPC no checkout." },
    { q: "Que métodos de pagamento aceitam?",
      a: "Aceitamos todos os principais cartões de crédito e débito (Visa, Mastercard, Amex), transferências bancárias e PayPal. Pagamentos protegidos por Stripe. Moedas: EUR, USD e GBP." },
    { q: "Quão rápido respondem a pedidos?",
      a: "O nosso suporte por WhatsApp está disponível 24 horas por dia, 7 dias por semana. Emails recebem resposta detalhada num dia útil." },
    { q: "Para que marcas de equipamento de cozinha comercial têm peças?",
      a: "A HDO Global Trade disponibiliza peças para todas as grandes marcas de equipamento de cozinha comercial, incluindo Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama e muitas mais. Se não encontrar a sua marca, contacte-nos — a nossa equipa de sourcing pode localizar peças para praticamente qualquer fabricante." },
    { q: "Oferecem suporte técnico para a instalação de peças?",
      a: "Sim. A nossa equipa técnica está disponível para ajudar na identificação de peças, verificação de compatibilidade e orientação básica de instalação. Contacte-nos via WhatsApp para assistência imediata, ou envie-nos fotos do seu equipamento e da peça por email." },
    { q: "Posso rastrear a minha encomenda após o envio?",
      a: "Sim. Cada encomenda enviada pela HDO Global Trade inclui um número de rastreamento completo enviado para o seu email. Pode acompanhar o progresso do envio em tempo real desde o despacho até à entrega." },
    { q: "Enviam para a Áustria, Alemanha e outros países de língua alemã?",
      a: "Sim, enviamos para toda a Europa, incluindo Áustria, Alemanha, Suíça e todos os estados membros da UE. As entregas para a Áustria e Alemanha chegam normalmente em 3–5 dias úteis. Clientes empresariais da UE com NIF válido podem beneficiar de isenção de IVA intracomunitária." },
  ],
  de: [
    { q: "Versenden Sie Ersatzteile weltweit?",
      a: "Ja, HDO Trade versendet geprüfte Ersatzteile weltweit mit schneller Lieferung und vollständiger Sendungsverfolgung vom Versand bis zur Zustellung." },
    { q: "Werden alle Ersatzteile vor dem Versand getestet?",
      a: "Jedes unter der Marke HDO TRADE verkaufte Ersatzteil wird von unserem zertifizierten Techniker-Team einzeln geprüft und durchläuft strenge Qualitätskontrollen, bevor es unser Lager verlässt." },
    { q: "Wie finde ich das richtige Ersatzteil für meine Maschine?",
      a: "Suchen Sie in unserem Shop nach Hersteller, Kategorie oder Teilenummer. Filtern Sie nach Gerätetyp — Spülmaschine, Mixer, Entsafter, Gemüseschneider oder Küchenarmatur. Unser Import-Team hilft Ihnen per WhatsApp beim Auffinden jedes Teils." },
    { q: "Sind Ihre Ersatzteile original OEM oder kompatible Nachbauteile?",
      a: "Wir führen sowohl originale OEM-Teile als auch hochwertige kompatible Alternativen. Jede Produktbeschreibung gibt klar an, ob es sich um ein Original oder ein kompatibles Teil handelt." },
    { q: "Wie lange dauert die Lieferung?",
      a: "Lieferungen innerhalb der EU dauern in der Regel 3–7 Werktage. Expresslieferung ist an der Kasse verfügbar. Internationale Bestellungen außerhalb der EU kommen in 7–14 Werktagen an." },
    { q: "Liefern Sie Ersatzteile für gewerbliche Küchengeräte?",
      a: "Ja. Wir sind spezialisiert auf Ersatzteile für professionelle und gewerbliche Küchengeräte: Gastro-Spülmaschinen, Standmixer, Entsafter, Gemüseschneider und Gastro-Küchenarmaturen. Wir beliefern Restaurants, Hotels, Catering-Unternehmen und Reparaturtechniker." },
    { q: "Wo finde ich die Modellnummer meiner Maschine?",
      a: "Die Modellnummer befindet sich meist auf einem Aufkleber auf der Rückseite, Unterseite oder innen an der Tür des Geräts. Teilen Sie sie uns per WhatsApp mit und wir bestätigen sofort die kompatiblen Teile." },
    { q: "Wie lautet Ihre Rückgabepolitik?",
      a: "Wir akzeptieren Rücksendungen innerhalb von 14 Tagen nach Lieferung für unbenutzte Teile im Originalzustand. Bei beschädigten oder falsch gelieferten Teilen ersetzen wir das Teil oder erstatten den vollen Kaufpreis." },
    { q: "Bieten Sie Großhandelspreise für Gewerbebetriebe an?",
      a: "Ja, wir bieten wettbewerbsfähige Großhandelspreise für Restaurants, Reparaturwerkstätten, Hotelgruppen und Einkaufsabteilungen. Kontaktieren Sie uns per WhatsApp oder E-Mail für ein individuelles Angebot." },
    { q: "Kann ich eine MwSt.-Rechnung erhalten?",
      a: "Ja. Alle Bestellungen erhalten automatisch eine MwSt.-konforme Rechnung per E-Mail. EU-Geschäftskunden mit gültiger USt-IdNr. können von der innergemeinschaftlichen Steuerbefreiung profitieren." },
    { q: "Welche Zahlungsmethoden akzeptieren Sie?",
      a: "Wir akzeptieren alle gängigen Kredit- und Debitkarten (Visa, Mastercard, Amex), Banküberweisungen und PayPal. Transaktionen werden durch Stripe gesichert. Währungen: EUR, USD, GBP." },
    { q: "Wie schnell antworten Sie auf Anfragen?",
      a: "Unser WhatsApp-Support ist 24 Stunden am Tag, 7 Tage die Woche für dringende Teileanfragen verfügbar. E-Mails erhalten eine ausführliche Antwort innerhalb eines Werktages." },
    { q: "Für welche Marken gewerblicher Küchengeräte führen Sie Ersatzteile?",
      a: "HDO Global Trade führt Ersatzteile für alle großen Marken gewerblicher Küchengeräte, darunter Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama und viele mehr. Wenn Sie Ihre Marke nicht finden, kontaktieren Sie uns — unser Beschaffungsteam kann Teile für praktisch jeden Hersteller weltweit finden." },
    { q: "Bieten Sie technischen Support bei der Teileinstallation?",
      a: "Ja. Unser technisches Team steht Ihnen bei der Teileidentifikation, Kompatibilitätsprüfung und grundlegenden Installationsanleitung zur Verfügung. Kontaktieren Sie uns per WhatsApp für sofortige Hilfe oder senden Sie uns Fotos Ihres Geräts per E-Mail." },
    { q: "Kann ich meine Bestellung nach dem Versand verfolgen?",
      a: "Selbstverständlich. Jede Bestellung von HDO Global Trade enthält eine vollständige Sendungsverfolgungsnummer, die an Ihre registrierte E-Mail-Adresse gesendet wird. Sie können den Fortschritt Ihrer Sendung in Echtzeit vom Versand bis zur Zustellung verfolgen." },
    { q: "Liefern Sie nach Österreich, Deutschland und in andere deutschsprachige Länder?",
      a: "Ja, wir liefern europaweit, einschließlich Österreich, Deutschland, Schweiz und alle EU-Mitgliedstaaten. Lieferungen nach Österreich und Deutschland kommen in der Regel innerhalb von 3–5 Werktagen an. EU-Geschäftskunden mit gültiger USt-IdNr. können von der innergemeinschaftlichen Steuerbefreiung profitieren." },
  ],
  fr: [
    { q: "Expédiez-vous les pièces dans le monde entier?",
      a: "Oui, HDO Trade expédie des pièces testées dans le monde entier avec livraison rapide et suivi complet de l'expédition à la livraison." },
    { q: "Toutes les pièces sont-elles testées avant expédition?",
      a: "Chaque pièce vendue sous la marque HDO TRADE est testée individuellement par notre équipe technique certifiée et passe un contrôle qualité strict avant de quitter notre entrepôt." },
    { q: "Comment trouver la bonne pièce pour ma machine?",
      a: "Recherchez par fabricant, catégorie ou référence dans notre boutique. Filtrez par type d'appareil — lave-vaisselle, mixeur, centrifugeuse, coupe-légumes ou robinetterie. Notre équipe import vous aide via WhatsApp pour trouver n'importe quelle pièce." },
    { q: "Vos pièces sont-elles originales OEM ou compatibles?",
      a: "Nous proposons à la fois des pièces originales OEM et des alternatives compatibles de haute qualité. Chaque fiche produit indique clairement s'il s'agit d'une pièce originale ou compatible." },
    { q: "Quel est le délai de livraison?",
      a: "Les livraisons en France et dans l'UE prennent généralement 3 à 7 jours ouvrés. Des options d'expédition express sont disponibles à la commande. Les commandes hors UE arrivent en 7 à 14 jours ouvrés." },
    { q: "Fournissez-vous des pièces pour équipements de cuisine professionnelle?",
      a: "Oui. Nous sommes spécialisés dans les pièces pour équipements de cuisine professionnelle: lave-vaisselle industriels, batteurs sur socle, centrifugeuses, coupe-légumes et robinetterie de cuisine pro. Nous servons les restaurants, hôtels, traiteurs et techniciens de réparation." },
    { q: "Comment trouver le numéro de modèle de ma machine?",
      a: "Le numéro de modèle se trouve généralement sur une étiquette à l'arrière ou sous la machine, à l'intérieur de la porte ou sur le moteur. Partagez-le via WhatsApp et nous confirmons immédiatement les pièces compatibles." },
    { q: "Quelle est votre politique de retour?",
      a: "Nous acceptons les retours dans les 14 jours suivant la livraison pour les pièces non utilisées en état d'origine. Si une pièce arrive endommagée ou non conforme, nous la remplaçons ou remboursons intégralement." },
    { q: "Proposez-vous des tarifs grossiste pour les professionnels?",
      a: "Oui. Nous offrons des prix compétitifs pour les restaurants, ateliers de réparation, groupes hôteliers et équipes achats en volume. Contactez-nous via WhatsApp ou email pour un devis personnalisé." },
    { q: "Puis-je obtenir une facture avec TVA?",
      a: "Oui. Toutes les commandes génèrent automatiquement une facture conforme à la TVA envoyée par email. Les clients professionnels UE avec numéro de TVA valide peuvent bénéficier de l'exonération intracommunautaire." },
    { q: "Quels modes de paiement acceptez-vous?",
      a: "Nous acceptons toutes les cartes bancaires (Visa, Mastercard, Amex), virements et PayPal. Paiements sécurisés par Stripe. Devises: EUR, USD, GBP." },
    { q: "Quel est le délai de réponse?",
      a: "Notre support WhatsApp est disponible 24h/24, 7j/7 pour les demandes urgentes. Les emails reçoivent une réponse détaillée en un jour ouvrable." },
    { q: "Pour quelles marques d'équipements de cuisine proposez-vous des pièces?",
      a: "HDO Global Trade propose des pièces pour toutes les grandes marques d'équipements de cuisine professionnelle, notamment Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama et bien d'autres. Si vous ne trouvez pas votre marque, contactez-nous — notre équipe d'approvisionnement peut localiser des pièces pour pratiquement tout fabricant." },
    { q: "Proposez-vous un support technique pour l'installation des pièces?",
      a: "Oui. Notre équipe technique est disponible pour l'identification des pièces, la vérification de compatibilité et les conseils d'installation de base. Contactez-nous via WhatsApp pour une assistance immédiate, ou envoyez-nous des photos de votre équipement par email." },
    { q: "Puis-je suivre ma commande après expédition?",
      a: "Absolument. Chaque commande expédiée par HDO Global Trade inclut un numéro de suivi complet envoyé à votre adresse email. Vous pouvez suivre la progression de votre envoi en temps réel, de l'expédition à la livraison." },
    { q: "Livrez-vous en Autriche, en Allemagne et dans d'autres pays germanophones?",
      a: "Oui, nous livrons dans toute l'Europe, y compris l'Autriche, l'Allemagne, la Suisse et tous les États membres de l'UE. Les livraisons en Autriche et en Allemagne arrivent généralement sous 3 à 5 jours ouvrés. Les clients professionnels UE avec un numéro de TVA valide peuvent bénéficier de l'exonération intracommunautaire." },
  ],
  es: [
    { q: "¿Envían repuestos a todo el mundo?",
      a: "Sí, HDO Trade envía repuestos testados globalmente con entrega rápida y seguimiento completo desde el despacho hasta la entrega." },
    { q: "¿Todos los repuestos se prueban antes del envío?",
      a: "Cada repuesto vendido bajo la marca HDO TRADE es probado individualmente por nuestro equipo técnico certificado y pasa un control de calidad estricto antes de salir de nuestro almacén." },
    { q: "¿Cómo encuentro el repuesto correcto para mi máquina?",
      a: "Busque por fabricante, categoría o referencia en nuestra tienda. Filtre por tipo de equipo — lavavajillas, batidora, licuadora, cortaverduras o grifería. Nuestro equipo de importación le ayuda vía WhatsApp para localizar cualquier pieza." },
    { q: "¿Sus repuestos son originales OEM o compatibles?",
      a: "Disponemos tanto de piezas originales OEM como de alternativas compatibles de alta calidad. Cada ficha de producto indica claramente si es original o compatible." },
    { q: "¿Cuánto tarda la entrega?",
      a: "Las entregas en España y la UE tardan entre 3 y 7 días hábiles. El envío exprés está disponible en el checkout. Los pedidos internacionales fuera de la UE llegan en 7–14 días hábiles." },
    { q: "¿Suministran repuestos para maquinaria de hostelería?",
      a: "Sí. Estamos especializados en repuestos para equipos de cocina profesional: lavavajillas industriales, batidoras de pie, licuadoras, cortaverduras y grifería de cocina profesional. Servimos a restaurantes, hoteles, empresas de catering y técnicos de reparación." },
    { q: "¿Cómo localizo el número de modelo de mi máquina?",
      a: "El número de modelo suele estar en una etiqueta en la parte trasera o inferior del equipo, dentro de la puerta o en el motor. Compártalo por WhatsApp y confirmamos de inmediato los repuestos compatibles." },
    { q: "¿Cuál es su política de devoluciones?",
      a: "Aceptamos devoluciones en los 14 días siguientes a la entrega para piezas no utilizadas en estado original. Si una pieza llega dañada o no corresponde a la descripción, la sustituimos o reembolsamos íntegramente." },
    { q: "¿Ofrecen precios mayoristas para empresas?",
      a: "Sí. Ofrecemos precios competitivos para restaurantes, talleres de reparación, cadenas hoteleras y equipos de compras en volumen. Contáctenos por WhatsApp o email para un presupuesto personalizado." },
    { q: "¿Puedo obtener una factura con IVA?",
      a: "Sí. Todos los pedidos generan automáticamente una factura conforme al IVA enviada a su email. Los clientes empresariales de la UE con número de IVA válido pueden beneficiarse de la exención intracomunitaria." },
    { q: "¿Qué métodos de pago aceptan?",
      a: "Aceptamos todas las tarjetas principales (Visa, Mastercard, Amex), transferencias bancarias y PayPal. Pagos protegidos por Stripe. Monedas: EUR, USD, GBP." },
    { q: "¿Cuánto tardan en responder?",
      a: "Nuestro soporte WhatsApp está disponible 24 horas al día, 7 días a la semana. Los emails reciben respuesta detallada en un día hábil." },
    { q: "¿Para qué marcas de equipos de cocina tienen repuestos?",
      a: "HDO Global Trade dispone de repuestos para todas las grandes marcas de equipos de cocina comercial, incluyendo Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama y muchas más. Si no encuentra su marca, contáctenos — nuestro equipo de sourcing puede localizar piezas para prácticamente cualquier fabricante a nivel mundial." },
    { q: "¿Ofrecen soporte técnico para la instalación de piezas?",
      a: "Sí. Nuestro equipo técnico está disponible para ayudar con la identificación de piezas, verificación de compatibilidad y orientación básica de instalación. Contáctenos por WhatsApp para asistencia inmediata, o envíenos fotos de su equipo por email." },
    { q: "¿Puedo rastrear mi pedido después del envío?",
      a: "Por supuesto. Cada pedido enviado por HDO Global Trade incluye un número de seguimiento completo enviado a su email registrado. Puede monitorear el progreso de su envío en tiempo real desde el despacho hasta la entrega." },
    { q: "¿Envían a Austria, Alemania y otros países de habla alemana?",
      a: "Sí, enviamos a toda Europa, incluyendo Austria, Alemania, Suiza y todos los estados miembros de la UE. Las entregas a Austria y Alemania llegan normalmente en 3–5 días hábiles. Los clientes empresariales de la UE con número de IVA válido pueden beneficiarse de la exención intracomunitaria." },
  ],
  he: [
    { q: "האם אתם שולחים חלקי חילוף לכל העולם?",
      a: "כן, HDO Trade שולחת חלקי חילוף מבוקרים לכל העולם עם משלוח מהיר ומעקב מלא מרגע המשלוח ועד המסירה." },
    { q: "האם כל חלקי החילוף נבדקים לפני המשלוח?",
      a: "כל חלק חילוף נבדק בנפרד על ידי הצוות הטכני המוסמך שלנו ועובר בקרת איכות קפדנית לפני שיוצא מהמחסן." },
    { q: "איך אני מוצא את החלק הנכון למכשיר שלי?",
      a: "חפשו לפי יצרן, קטגוריה או מספר חלק בחנות שלנו. ניתן לסנן לפי סוג מכשיר — מדיח כלים, מיקסר, מסחטה, קוצץ ירקות או ברז מטבח. אם לא מצאתם — שלחו הודעת WhatsApp וצוות הייבוא שלנו יאתר עבורכם." },
    { q: "האם החלקים הם מקוריים OEM או תואמים?",
      a: "אנחנו מספקים הן חלקים מקוריים OEM והן חלופות תואמות באיכות גבוהה. כל דף מוצר מציין בבירור אם החלק מקורי או תואם." },
    { q: "כמה זמן לוקחת המשלוח?",
      a: "משלוחים לתוך האיחוד האירופי לוקחים בדרך כלל 3–7 ימי עסקים. יש אפשרות משלוח מהיר בתשלום. הזמנות בין-לאומיות מחוץ לאיחוד מגיעות תוך 7–14 ימי עסקים." },
    { q: "האם אתם מספקים חלקי חילוף לציוד מטבח מסחרי?",
      a: "כן. אנחנו מתמחים בחלקי חילוף לציוד מטבח מקצועי ומסחרי: מדיחי כלים תעשייתיים, מיקסרים, מסחטות, קוצצי ירקות וברזי מטבח מקצועיים. אנו משרתים מסעדות, מלונות, חברות קייטרינג וטכנאי תיקונים." },
    { q: "איך אני מוצא את מספר הדגם של המכשיר שלי?",
      a: "מספר הדגם מופיע בדרך כלל על מדבקה בגב המכשיר, בתחתיתו, בתוך הדלת או על המנוע. שתפו אותנו במספר דרך WhatsApp ונאשר מיד את החלקים התואמים." },
    { q: "מה מדיניות ההחזרות שלכם?",
      a: "אנחנו מקבלים החזרות תוך 14 יום ממועד קבלת ההזמנה לחלקים שלא נעשה בהם שימוש במצבם המקורי. אם חלק הגיע פגום או לא תואם לתיאור — נחליף אותו או נחזיר את התשלום במלואו." },
    { q: "האם אתם מציעים מחירי סיטונאות לעסקים?",
      a: "כן. אנחנו מציעים מחירים תחרותיים למסעדות, מוסכי תיקונים, רשתות מלונאות וצוותי רכש בהזמנות גדולות. פנו אלינו ב-WhatsApp או באימייל לקבלת הצעת מחיר מותאמת." },
    { q: "האם ניתן לקבל חשבונית מס?",
      a: "כן. כל הזמנה מייצרת אוטומטית חשבונית מס שנשלחת לאימייל שלכם. לקוחות עסקיים מהאיחוד האירופי עם מספר מע\"מ תקף עשויים להיות זכאים לפטור ממע\"מ עסקאות תוך-קהילתי." },
    { q: "אילו אמצעי תשלום אתם מקבלים?",
      a: "אנחנו מקבלים את כל כרטיסי האשראי העיקריים (Visa, Mastercard, Amex), העברות בנקאיות ו-PayPal. התשלומים מאובטחים על ידי Stripe. מטבעות: EUR, USD, GBP." },
    { q: "תוך כמה זמן אתם מגיבים?",
      a: "תמיכת הוואטסאפ זמינה 24 שעות ביממה, 7 ימים בשבוע לבקשות דחופות. אימיילים מקבלים תשובה מפורטת תוך יום עסקים." },
    { q: "לאילו מותגים של ציוד מטבח מסחרי יש לכם חלקי חילוף?",
      a: "HDO Global Trade מספקת חלקי חילוף לכל המותגים הגדולים של ציוד מטבח מסחרי, כולל Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama ועוד רבים. אם לא מצאתם את המותג שלכם, צרו קשר — צוות המקורות שלנו יכול לאתר חלקים כמעט לכל יצרן בעולם." },
    { q: "האם אתם מספקים תמיכה טכנית להתקנת חלקים?",
      a: "כן. הצוות הטכני שלנו זמין לסיוע בזיהוי חלקים, אימות תאימות והדרכת התקנה בסיסית. פנו אלינו ב-WhatsApp לעזרה מיידית, או שלחו לנו תמונות של הציוד שלכם באימייל." },
    { q: "האם אפשר לעקוב אחרי ההזמנה לאחר המשלוח?",
      a: "בהחלט. כל הזמנה שנשלחת מ-HDO Global Trade כוללת מספר מעקב מלא שנשלח לכתובת האימייל שלכם. ניתן לעקוב אחר התקדמות המשלוח בזמן אמת מרגע השליחה ועד למסירה." },
    { q: "האם אתם שולחים לאוסטריה, גרמניה ומדינות דוברות גרמנית?",
      a: "כן, אנחנו שולחים לכל רחבי אירופה כולל אוסטריה, גרמניה, שוויץ וכל מדינות האיחוד האירופי. משלוחים לאוסטריה ולגרמניה מגיעים בדרך כלל תוך 3–5 ימי עסקים. לקוחות עסקיים מהאיחוד האירופי עם מספר מע\"מ תקף יכולים ליהנות מפטור ממע\"מ תוך-קהילתי." },
  ],
  it: [
    { q: "Spedite i ricambi in tutto il mondo?",
      a: "Sì, HDO Trade spedisce ricambi testati in tutto il mondo con consegna rapida e tracciamento completo dalla spedizione alla consegna." },
    { q: "Tutti i ricambi vengono testati prima della spedizione?",
      a: "Ogni ricambio venduto con il marchio HDO TRADE viene testato singolarmente dal nostro team tecnico certificato e sottoposto a uno stretto controllo qualità prima di lasciare il nostro magazzino." },
    { q: "Come trovo il ricambio giusto per la mia macchina?",
      a: "Cerca per produttore, categoria o riferimento nel nostro negozio. Puoi filtrare per tipo di apparecchiatura — lavastoviglie, impastatrice, spremiagrumi, taglialegumi o rubinetteria. Se non lo trovi, inviaci un messaggio su WhatsApp e lo individuiamo per te." },
    { q: "I vostri ricambi sono originali OEM o compatibili?",
      a: "Disponiamo sia di pezzi originali OEM sia di alternative compatibili di alta qualità. Ogni scheda prodotto indica chiaramente se si tratta di un pezzo originale o compatibile." },
    { q: "Quanto tempo richiede la consegna?",
      a: "Le consegne in Italia e nell'UE richiedono in genere 3–7 giorni lavorativi. La spedizione espressa è disponibile al checkout. Gli ordini internazionali fuori dall'UE arrivano in 7–14 giorni lavorativi." },
    { q: "Fornite ricambi per attrezzature da cucina commerciale?",
      a: "Sì. Siamo specializzati in ricambi per attrezzature da cucina professionale: lavastoviglie industriali, impastatrici planetarie, spremiagrumi, taglialegumi e rubinetteria da cucina professionale. Serviamo ristoranti, hotel, catering e tecnici di riparazione." },
    { q: "Come trovo il numero di modello della mia macchina?",
      a: "Il numero di modello si trova di solito su un'etichetta sul retro o sotto l'apparecchio, all'interno della porta o sul motore. Condividilo con noi via WhatsApp e confermiamo subito i ricambi compatibili." },
    { q: "Qual è la vostra politica di reso?",
      a: "Accettiamo resi entro 14 giorni dalla consegna per i pezzi non utilizzati nelle condizioni originali. Se un ricambio arriva danneggiato o non corrisponde alla descrizione, lo sostituiamo o rimborsiamo integralmente." },
    { q: "Offrite prezzi all'ingrosso per le aziende?",
      a: "Sì. Offriamo prezzi competitivi per ristoranti, officine di riparazione, catene alberghiere e team acquisti con volumi. Contattateci via WhatsApp o email per un preventivo personalizzato." },
    { q: "Posso ricevere una fattura con IVA?",
      a: "Sì. Tutti gli ordini generano automaticamente una fattura conforme all'IVA inviata via email. I clienti aziendali dell'UE con un numero di partita IVA valido possono beneficiare dell'esenzione intracomunitaria." },
    { q: "Quali metodi di pagamento accettate?",
      a: "Accettiamo tutte le principali carte di credito e debito (Visa, Mastercard, Amex), bonifici bancari e PayPal. Pagamenti protetti da Stripe. Valute: EUR, USD, GBP." },
    { q: "Quanto tempo impiegate a rispondere?",
      a: "Il nostro supporto WhatsApp è disponibile 24 ore su 24, 7 giorni su 7 per richieste urgenti. Le email ricevono una risposta dettagliata entro un giorno lavorativo." },
    { q: "Per quali marche di attrezzature da cucina avete ricambi?",
      a: "HDO Global Trade dispone di ricambi per tutte le principali marche di attrezzature da cucina commerciale, tra cui Electrolux Professional, Santos, Sirman, Dynamic, Robot-Coupe, Hobart, Rational, Winterhalter, Meiko, Sammic, Dito Sama e molte altre. Se non trovi la tua marca, contattaci — il nostro team di sourcing può individuare pezzi per praticamente qualsiasi produttore a livello mondiale." },
    { q: "Offrite supporto tecnico per l'installazione dei ricambi?",
      a: "Sì. Il nostro team tecnico è disponibile per l'identificazione dei pezzi, la verifica di compatibilità e le indicazioni di base per l'installazione. Contattateci via WhatsApp per assistenza immediata, oppure inviateci foto della vostra attrezzatura via email." },
    { q: "Posso tracciare il mio ordine dopo la spedizione?",
      a: "Certamente. Ogni ordine spedito da HDO Global Trade include un numero di tracciamento completo inviato alla vostra email registrata. Potete seguire l'avanzamento della spedizione in tempo reale dalla partenza alla consegna." },
    { q: "Spedite in Austria, Germania e altri paesi di lingua tedesca?",
      a: "Sì, spediamo in tutta Europa, inclusi Austria, Germania, Svizzera e tutti gli stati membri dell'UE. Le consegne in Austria e Germania arrivano di solito entro 3–5 giorni lavorativi. I clienti aziendali dell'UE con partita IVA valida possono beneficiare dell'esenzione IVA intracomunitaria." },
  ],
};

// Questions that reduce purchase friction, shown on the home page:
// 0 = international shipping, 1 = quality tested, 2 = find the right part,
// 4 = delivery time, 7 = returns policy. The full list lives on /faq.
export const FEATURED_FAQ_INDICES = [0, 1, 2, 4, 7];

export function getFeaturedFaqs(faqs) {
  return faqs.filter((_, idx) => FEATURED_FAQ_INDICES.includes(idx));
}

export default function FAQSchema({ lang = "en", featured = false }) {
  const allFaqs = FAQS[lang] || FAQS.en;
  const faqs = featured ? getFeaturedFaqs(allFaqs) : allFaqs;

  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
