// FAQPage JSON-LD — gives expandable FAQ rich snippets directly in Google search results
// These appear as dropdown accordions under your listing — takes up much more space = more clicks

export const FAQS = {
  en: [
    { q: "Do you ship spare parts worldwide?",
      a: "Yes, HDO Trade ships tested spare parts to customers worldwide. We offer fast international shipping with full order tracking from dispatch to delivery." },
    { q: "Are all spare parts tested before shipping?",
      a: "Every spare part sold under the HDO TRADE brand is individually tested by our certified technical team and passes strict quality control checks before it leaves our warehouse." },
    { q: "How can I find the right spare part for my machine?",
      a: "Search by manufacturer, category, or part reference number in our shop. You can also filter by machine type — dishwasher, mixer, juicer, vegetable cutter, or kitchen tap. If you still can't find the exact part, message our import team via WhatsApp and we will source it for you." },
    { q: "Are your spare parts original OEM or compatible aftermarket?",
      a: "We stock both original OEM parts and high-quality compatible aftermarket alternatives. Each product listing clearly states whether it is original or compatible, so you can make the right choice for your machine and budget." },
    { q: "How long does delivery take?",
      a: "Standard delivery within the EU takes 3–7 business days. Express shipping options are available at checkout. International orders outside the EU typically arrive within 7–14 business days depending on destination." },
    { q: "Do you supply spare parts for commercial kitchen equipment?",
      a: "Yes. We specialise in spare parts for professional and commercial kitchen equipment including commercial dishwashers, stand mixers, juicers, vegetable cutters, and commercial kitchen taps. We serve restaurants, hotels, catering companies, and repair technicians." },
    { q: "How do I find my machine's model number?",
      a: "The model number is usually printed on a label on the back or underside of your machine, inside the door, or on the motor housing. It may start with letters followed by numbers (e.g. DW-450, JX-200). Share it with us via WhatsApp and we'll confirm the compatible parts immediately." },
    { q: "What is your returns policy?",
      a: "We accept returns within 14 days of delivery for unused parts in original condition. If a part arrives damaged or is not as described, we will replace it or issue a full refund at no cost to you. Contact us via WhatsApp or email to initiate a return." },
    { q: "Do you offer bulk or wholesale pricing for businesses?",
      a: "Yes. We offer competitive wholesale pricing for restaurants, repair workshops, hotel groups, and procurement teams ordering in volume. Contact our commercial team via WhatsApp or email for a custom quote." },
    { q: "Can I get a VAT invoice for my purchase?",
      a: "Yes. All orders automatically generate a VAT-compliant invoice sent to your email. For EU business customers with a VAT number, intra-community tax exemption may apply — enter your VAT number at checkout." },
    { q: "What payment methods do you accept?",
      a: "We accept all major credit and debit cards (Visa, Mastercard, Amex), bank transfers, and PayPal. Transactions are secured by Stripe. Currencies supported: EUR, USD, and GBP." },
    { q: "How quickly do you respond to enquiries?",
      a: "Our WhatsApp support is available 24 hours a day, 7 days a week for urgent part requests. Email enquiries receive a detailed response within one business day." },
  ],
  pt: [
    { q: "Enviam peças sobresselentes para todo o mundo?",
      a: "Sim, a HDO Trade envia peças testadas para clientes em todo o mundo com entrega rápida e rastreamento completo desde o despacho até à entrega." },
    { q: "Todas as peças são testadas antes do envio?",
      a: "Cada peça vendida sob a marca HDO TRADE é testada individualmente pela nossa equipa técnica certificada e passa por rigoroso controlo de qualidade antes de sair do armazém." },
    { q: "Como posso encontrar a peça certa para a minha máquina?",
      a: "Pesquise por fabricante, categoria ou referência na nossa loja. Pode filtrar por tipo de equipamento — máquina de lavar louça, batedeira, centrifugadora, cortador de legumes ou torneira de cozinha. Se não encontrar, envie-nos mensagem via WhatsApp e localizamos a peça por si." },
    { q: "As vossas peças são originais OEM ou compatíveis?",
      a: "Temos tanto peças originais OEM como alternativas compatíveis de alta qualidade. Cada produto indica claramente se é original ou compatível, para escolher o mais adequado à sua máquina e orçamento." },
    { q: "Quanto tempo demora a entrega?",
      a: "As entregas em Portugal e na UE demoram normalmente 3 a 7 dias úteis. Há opções de envio expresso disponíveis no checkout. Encomendas internacionais fora da UE demoram entre 7 a 14 dias úteis." },
    { q: "Fornecem peças para equipamento de cozinha industrial?",
      a: "Sim, especializamo-nos em peças para equipamento de cozinha profissional e industrial: máquinas de lavar louça comerciais, batedeiras industriais, centrifugadoras, cortadores de legumes e torneiras de cozinha. Servimos restaurantes, hotéis, empresas de catering e técnicos de reparação." },
    { q: "Como encontro o número de modelo da minha máquina?",
      a: "O número de modelo está normalmente numa etiqueta na parte traseira ou inferior da máquina, dentro da porta ou no motor. Partilhe-o connosco via WhatsApp e confirmamos imediatamente as peças compatíveis." },
    { q: "Qual é a política de devoluções?",
      a: "Aceitamos devoluções até 14 dias após a entrega para peças não utilizadas em estado original. Se uma peça chegar danificada ou não corresponder à descrição, substituímos ou reembolsamos na totalidade sem custo para si." },
    { q: "Oferecem preços grossistas para empresas?",
      a: "Sim, oferecemos preços competitivos para restaurantes, oficinas de reparação, cadeias hoteleiras e equipas de compras em volume. Contacte-nos via WhatsApp ou email para um orçamento personalizado." },
    { q: "Posso obter fatura com IVA?",
      a: "Sim. Todas as encomendas geram automaticamente uma fatura com IVA enviada para o seu email. Clientes empresariais da UE com número de IVA válido podem beneficiar de isenção intracomunitária — introduza o NIF/NIPC no checkout." },
    { q: "Que métodos de pagamento aceitam?",
      a: "Aceitamos todos os principais cartões de crédito e débito (Visa, Mastercard, Amex), transferências bancárias e PayPal. Pagamentos protegidos por Stripe. Moedas: EUR, USD e GBP." },
    { q: "Quão rápido respondem a pedidos?",
      a: "O nosso suporte por WhatsApp está disponível 24 horas por dia, 7 dias por semana. Emails recebem resposta detalhada num dia útil." },
  ],
  de: [
    { q: "Versenden Sie Ersatzteile weltweit?",
      a: "Ja, HDO Trade versendet geprüfte Ersatzteile weltweit mit schneller Lieferung und vollständiger Sendungsverfolgung vom Versand bis zur Zustellung." },
    { q: "Werden alle Ersatzteile vor dem Versand getestet?",
      a: "Jedes unter der Marke HDO TRADE verkaufte Ersatzteil wird von unserem zertifizierten Techniker-Team einzeln geprüft und durchläuft strenge Qualitätskontrollen, bevor es unser Lager verlässt." },
    { q: "Wie finde ich das richtige Ersatzteil für meine Maschine?",
      a: "Suchen Sie in unserem Shop nach Hersteller, Kategorie oder Teilenummer. Filtern Sie nach Gerätetyp — Spülmaschine, Mixer, Entsafter, Gemüseschneider oder Küchenarmatur. Unser Import-Team hilft Ihnen per WhatsApp beim Auffinden jedes Teils." },
    { q: "Sind Ihre Ersatzteile original OEM oder kompatible Nachbauteile?",
      a: "Wir führen sowohl originale OEM-Teile als auch hochwertige kompatible Alternativen. Jede Produktbeschreibung gibt klar an, ob es sich um ein Original oder ein kompatibles Teil handelt." },
    { q: "Wie lange dauert die Lieferung?",
      a: "Lieferungen innerhalb der EU dauern in der Regel 3–7 Werktage. Expresslieferung ist an der Kasse verfügbar. Internationale Bestellungen außerhalb der EU kommen in 7–14 Werktagen an." },
    { q: "Liefern Sie Ersatzteile für gewerbliche Küchengeräte?",
      a: "Ja. Wir sind spezialisiert auf Ersatzteile für professionelle und gewerbliche Küchengeräte: Gastro-Spülmaschinen, Standmixer, Entsafter, Gemüseschneider und Gastro-Küchenarmaturen. Wir beliefern Restaurants, Hotels, Catering-Unternehmen und Reparaturtechniker." },
    { q: "Wo finde ich die Modellnummer meiner Maschine?",
      a: "Die Modellnummer befindet sich meist auf einem Aufkleber auf der Rückseite, Unterseite oder innen an der Tür des Geräts. Teilen Sie sie uns per WhatsApp mit und wir bestätigen sofort die kompatiblen Teile." },
    { q: "Wie lautet Ihre Rückgabepolitik?",
      a: "Wir akzeptieren Rücksendungen innerhalb von 14 Tagen nach Lieferung für unbenutzte Teile im Originalzustand. Bei beschädigten oder falsch gelieferten Teilen ersetzen wir das Teil oder erstatten den vollen Kaufpreis." },
    { q: "Bieten Sie Großhandelspreise für Gewerbebetriebe an?",
      a: "Ja, wir bieten wettbewerbsfähige Großhandelspreise für Restaurants, Reparaturwerkstätten, Hotelgruppen und Einkaufsabteilungen. Kontaktieren Sie uns per WhatsApp oder E-Mail für ein individuelles Angebot." },
    { q: "Kann ich eine MwSt.-Rechnung erhalten?",
      a: "Ja. Alle Bestellungen erhalten automatisch eine MwSt.-konforme Rechnung per E-Mail. EU-Geschäftskunden mit gültiger USt-IdNr. können von der innergemeinschaftlichen Steuerbefreiung profitieren." },
    { q: "Welche Zahlungsmethoden akzeptieren Sie?",
      a: "Wir akzeptieren alle gängigen Kredit- und Debitkarten (Visa, Mastercard, Amex), Banküberweisungen und PayPal. Transaktionen werden durch Stripe gesichert. Währungen: EUR, USD, GBP." },
    { q: "Wie schnell antworten Sie auf Anfragen?",
      a: "Unser WhatsApp-Support ist 24 Stunden am Tag, 7 Tage die Woche für dringende Teileanfragen verfügbar. E-Mails erhalten eine ausführliche Antwort innerhalb eines Werktages." },
  ],
  fr: [
    { q: "Expédiez-vous les pièces dans le monde entier?",
      a: "Oui, HDO Trade expédie des pièces testées dans le monde entier avec livraison rapide et suivi complet de l'expédition à la livraison." },
    { q: "Toutes les pièces sont-elles testées avant expédition?",
      a: "Chaque pièce vendue sous la marque HDO TRADE est testée individuellement par notre équipe technique certifiée et passe un contrôle qualité strict avant de quitter notre entrepôt." },
    { q: "Comment trouver la bonne pièce pour ma machine?",
      a: "Recherchez par fabricant, catégorie ou référence dans notre boutique. Filtrez par type d'appareil — lave-vaisselle, mixeur, centrifugeuse, coupe-légumes ou robinetterie. Notre équipe import vous aide via WhatsApp pour trouver n'importe quelle pièce." },
    { q: "Vos pièces sont-elles originales OEM ou compatibles?",
      a: "Nous proposons à la fois des pièces originales OEM et des alternatives compatibles de haute qualité. Chaque fiche produit indique clairement s'il s'agit d'une pièce originale ou compatible." },
    { q: "Quel est le délai de livraison?",
      a: "Les livraisons en France et dans l'UE prennent généralement 3 à 7 jours ouvrés. Des options d'expédition express sont disponibles à la commande. Les commandes hors UE arrivent en 7 à 14 jours ouvrés." },
    { q: "Fournissez-vous des pièces pour équipements de cuisine professionnelle?",
      a: "Oui. Nous sommes spécialisés dans les pièces pour équipements de cuisine professionnelle: lave-vaisselle industriels, batteurs sur socle, centrifugeuses, coupe-légumes et robinetterie de cuisine pro. Nous servons les restaurants, hôtels, traiteurs et techniciens de réparation." },
    { q: "Comment trouver le numéro de modèle de ma machine?",
      a: "Le numéro de modèle se trouve généralement sur une étiquette à l'arrière ou sous la machine, à l'intérieur de la porte ou sur le moteur. Partagez-le via WhatsApp et nous confirmons immédiatement les pièces compatibles." },
    { q: "Quelle est votre politique de retour?",
      a: "Nous acceptons les retours dans les 14 jours suivant la livraison pour les pièces non utilisées en état d'origine. Si une pièce arrive endommagée ou non conforme, nous la remplaçons ou remboursons intégralement." },
    { q: "Proposez-vous des tarifs grossiste pour les professionnels?",
      a: "Oui. Nous offrons des prix compétitifs pour les restaurants, ateliers de réparation, groupes hôteliers et équipes achats en volume. Contactez-nous via WhatsApp ou email pour un devis personnalisé." },
    { q: "Puis-je obtenir une facture avec TVA?",
      a: "Oui. Toutes les commandes génèrent automatiquement une facture conforme à la TVA envoyée par email. Les clients professionnels UE avec numéro de TVA valide peuvent bénéficier de l'exonération intracommunautaire." },
    { q: "Quels modes de paiement acceptez-vous?",
      a: "Nous acceptons toutes les cartes bancaires (Visa, Mastercard, Amex), virements et PayPal. Paiements sécurisés par Stripe. Devises: EUR, USD, GBP." },
    { q: "Quel est le délai de réponse?",
      a: "Notre support WhatsApp est disponible 24h/24, 7j/7 pour les demandes urgentes. Les emails reçoivent une réponse détaillée en un jour ouvrable." },
  ],
  es: [
    { q: "¿Envían repuestos a todo el mundo?",
      a: "Sí, HDO Trade envía repuestos testados globalmente con entrega rápida y seguimiento completo desde el despacho hasta la entrega." },
    { q: "¿Todos los repuestos se prueban antes del envío?",
      a: "Cada repuesto vendido bajo la marca HDO TRADE es probado individualmente por nuestro equipo técnico certificado y pasa un control de calidad estricto antes de salir de nuestro almacén." },
    { q: "¿Cómo encuentro el repuesto correcto para mi máquina?",
      a: "Busque por fabricante, categoría o referencia en nuestra tienda. Filtre por tipo de equipo — lavavajillas, batidora, licuadora, cortaverduras o grifería. Nuestro equipo de importación le ayuda vía WhatsApp para localizar cualquier pieza." },
    { q: "¿Sus repuestos son originales OEM o compatibles?",
      a: "Disponemos tanto de piezas originales OEM como de alternativas compatibles de alta calidad. Cada ficha de producto indica claramente si es original o compatible." },
    { q: "¿Cuánto tarda la entrega?",
      a: "Las entregas en España y la UE tardan entre 3 y 7 días hábiles. El envío exprés está disponible en el checkout. Los pedidos internacionales fuera de la UE llegan en 7–14 días hábiles." },
    { q: "¿Suministran repuestos para maquinaria de hostelería?",
      a: "Sí. Estamos especializados en repuestos para equipos de cocina profesional: lavavajillas industriales, batidoras de pie, licuadoras, cortaverduras y grifería de cocina profesional. Servimos a restaurantes, hoteles, empresas de catering y técnicos de reparación." },
    { q: "¿Cómo localizo el número de modelo de mi máquina?",
      a: "El número de modelo suele estar en una etiqueta en la parte trasera o inferior del equipo, dentro de la puerta o en el motor. Compártalo por WhatsApp y confirmamos de inmediato los repuestos compatibles." },
    { q: "¿Cuál es su política de devoluciones?",
      a: "Aceptamos devoluciones en los 14 días siguientes a la entrega para piezas no utilizadas en estado original. Si una pieza llega dañada o no corresponde a la descripción, la sustituimos o reembolsamos íntegramente." },
    { q: "¿Ofrecen precios mayoristas para empresas?",
      a: "Sí. Ofrecemos precios competitivos para restaurantes, talleres de reparación, cadenas hoteleras y equipos de compras en volumen. Contáctenos por WhatsApp o email para un presupuesto personalizado." },
    { q: "¿Puedo obtener una factura con IVA?",
      a: "Sí. Todos los pedidos generan automáticamente una factura conforme al IVA enviada a su email. Los clientes empresariales de la UE con número de IVA válido pueden beneficiarse de la exención intracomunitaria." },
    { q: "¿Qué métodos de pago aceptan?",
      a: "Aceptamos todas las tarjetas principales (Visa, Mastercard, Amex), transferencias bancarias y PayPal. Pagos protegidos por Stripe. Monedas: EUR, USD, GBP." },
    { q: "¿Cuánto tardan en responder?",
      a: "Nuestro soporte WhatsApp está disponible 24 horas al día, 7 días a la semana. Los emails reciben respuesta detallada en un día hábil." },
  ],
  he: [
    { q: "האם אתם שולחים חלקי חילוף לכל העולם?",
      a: "כן, HDO Trade שולחת חלקי חילוף מבוקרים לכל העולם עם משלוח מהיר ומעקב מלא מרגע המשלוח ועד המסירה." },
    { q: "האם כל חלקי החילוף נבדקים לפני המשלוח?",
      a: "כל חלק חילוף נבדק בנפרד על ידי הצוות הטכני המוסמך שלנו ועובר בקרת איכות קפדנית לפני שיוצא מהמחסן." },
    { q: "איך אני מוצא את החלק הנכון למכשיר שלי?",
      a: "חפשו לפי יצרן, קטגוריה או מספר חלק בחנות שלנו. ניתן לסנן לפי סוג מכשיר — מדיח כלים, מיקסר, מסחטה, קוצץ ירקות או ברז מטבח. אם לא מצאתם — שלחו הודעת WhatsApp וצוות הייבוא שלנו יאתר עבורכם." },
    { q: "האם החלקים הם מקוריים OEM או תואמים?",
      a: "אנחנו מספקים הן חלקים מקוריים OEM והן חלופות תואמות באיכות גבוהה. כל דף מוצר מציין בבירור אם החלק מקורי או תואם." },
    { q: "כמה זמן לוקחת המשלוח?",
      a: "משלוחים לתוך האיחוד האירופי לוקחים בדרך כלל 3–7 ימי עסקים. יש אפשרות משלוח מהיר בתשלום. הזמנות בין-לאומיות מחוץ לאיחוד מגיעות תוך 7–14 ימי עסקים." },
    { q: "האם אתם מספקים חלקי חילוף לציוד מטבח מסחרי?",
      a: "כן. אנחנו מתמחים בחלקי חילוף לציוד מטבח מקצועי ומסחרי: מדיחי כלים תעשייתיים, מיקסרים, מסחטות, קוצצי ירקות וברזי מטבח מקצועיים. אנו משרתים מסעדות, מלונות, חברות קייטרינג וטכנאי תיקונים." },
    { q: "איך אני מוצא את מספר הדגם של המכשיר שלי?",
      a: "מספר הדגם מופיע בדרך כלל על מדבקה בגב המכשיר, בתחתיתו, בתוך הדלת או על המנוע. שתפו אותנו במספר דרך WhatsApp ונאשר מיד את החלקים התואמים." },
    { q: "מה מדיניות ההחזרות שלכם?",
      a: "אנחנו מקבלים החזרות תוך 14 יום ממועד קבלת ההזמנה לחלקים שלא נעשה בהם שימוש במצבם המקורי. אם חלק הגיע פגום או לא תואם לתיאור — נחליף אותו או נחזיר את התשלום במלואו." },
    { q: "האם אתם מציעים מחירי סיטונאות לעסקים?",
      a: "כן. אנחנו מציעים מחירים תחרותיים למסעדות, מוסכי תיקונים, רשתות מלונאות וצוותי רכש בהזמנות גדולות. פנו אלינו ב-WhatsApp או באימייל לקבלת הצעת מחיר מותאמת." },
    { q: "האם ניתן לקבל חשבונית מס?",
      a: "כן. כל הזמנה מייצרת אוטומטית חשבונית מס שנשלחת לאימייל שלכם. לקוחות עסקיים מהאיחוד האירופי עם מספר מע\"מ תקף עשויים להיות זכאים לפטור ממע\"מ עסקאות תוך-קהילתי." },
    { q: "אילו אמצעי תשלום אתם מקבלים?",
      a: "אנחנו מקבלים את כל כרטיסי האשראי העיקריים (Visa, Mastercard, Amex), העברות בנקאיות ו-PayPal. התשלומים מאובטחים על ידי Stripe. מטבעות: EUR, USD, GBP." },
    { q: "תוך כמה זמן אתם מגיבים?",
      a: "תמיכת הוואטסאפ זמינה 24 שעות ביממה, 7 ימים בשבוע לבקשות דחופות. אימיילים מקבלים תשובה מפורטת תוך יום עסקים." },
  ],
};

export default function FAQSchema({ lang = "en" }) {
  const faqs = FAQS[lang] || FAQS.en;

  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
